ALTER SESSION SET NLS_DATE_FORMAT='DD-MM-YYYY';

SET SERVEROUTPUT ON;

--BOOKS relationship
CREATE TABLE BOOKS (
    TITLE VARCHAR2(60),
    WRITER VARCHAR2(60),
    ISBN NUMBER(10),
    CATEGORY VARCHAR2(60)
);

ALTER TABLE BOOKS
ADD CONSTRAINT PK PRIMARY KEY(ISBN); 

SELECT * FROM BOOKS;
DESC BOOKS;

--MEMBERS relationship
CREATE TABLE MEMBERS(
    ID NUMBER(5) ,
    NAME VARCHAR2(60),
    ADDRESS VARCHAR(60)
);

--A sequence in order to do auto increment for the field id
CREATE SEQUENCE members_seq
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1;

ALTER TABLE MEMBERS
ADD CONSTRAINT PKM PRIMARY KEY(ID);

SELECT * FROM MEMBERS;
DESC MEMBERS;

--BORROW relationship
CREATE TABLE BORROWS(
    BORROWID NUMBER(5) ,
    BOOKISBN NUMBER(10),
    BORROWDATE DATE,
    RETURNDATE DATE,
    AVALIABILLITY NUMBER(1),
    MEMBERID NUMBER(5)
    );
    
--A sequence in order to do auto increment for the field BORROWID
    CREATE SEQUENCE borrows_seq
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1;
    
ALTER TABLE BORROWS
ADD CONSTRAINT PKB PRIMARY KEY(BORROWID);

ALTER TABLE BORROWS
ADD CONSTRAINT FK_MID FOREIGN KEY(MEMBERID) REFERENCES MEMBERS(ID);

ALTER TABLE BORROWS
ADD CONSTRAINT FK_BOOK FOREIGN KEY(BOOKISBN) REFERENCES BOOKS(ISBN);

ALTER TABLE BORROWS
ADD DAYSBORROWED NUMBER(10);

--This column shows how many days is/was the book borrowed 
UPDATE BORROWS 
SET DAYSBORROWED=(SELECT TO_DATE(BORROWS.RETURNDATE,'DD-MM-YYYY')- 
TO_DATE (BORROWS.BORROWDATE,'DD-MM-YYYY')
FROM DUAL);

DESC BORROWS;
SELECT * FROM BORROWS;