ALTER TABLE BORROWS
DROP CONSTRAINT PKB;

ALTER TABLE BORROWS 
DROP CONSTRAINT FK_MID;

ALTER TABLE BORROWS
DROP CONSTRAINT FK_BOOK;

DROP TABLE BOOKS;
DROP TABLE BORROWS;
DROP TABLE MEMBERS;

DROP  SEQUENCE members_seq;
DROP SEQUENCE  borrows_seq;

DROP PACKAGE BOOK_DB;
DROP PACKAGE MEMBERS_DB;
DROP PACKAGE BPRROWS_DB;