SET SERVEROUTPUT ON; 
--A FUNCTION FOR RETURNING ISBNS OF A CATEGORY
CREATE OR REPLACE PACKAGE TYPES AS 
TYPE BOOK_CURSOR IS REF CURSOR;
END;
/

CREATE OR REPLACE FUNCTION BOOKPERCATEGORY(CAT IN BOOKS.CATEGORY%TYPE)
RETURN TYPES.BOOK_CURSOR
IS book TYPES.BOOK_CURSOR;

BEGIN
    OPEN book FOR 
    SELECT ISBN 
    FROM BOOKS WHERE CATEGORY=cat;
    RETURN book;
END BOOKPERCATEGORY;
/

SELECT BOOKPERCATEGORY('Art') FROM DUAL;

--FUNCTION TO FIND AVALIABILLITY FOR A BOOK
CREATE OR REPLACE FUNCTION CHECKAVALIABILLITY(ISBN_BOOK IN BOOKS.ISBN%TYPE)
RETURN NUMBER IS
check_avaliabillity NUMBER;

BEGIN 
    SELECT AVALIABILLITY INTO check_avaliabillity  
    FROM BORROWS b JOIN BOOKS bo ON b.BOOKISBN=bo.ISBN
    WHERE ISBN=ISBN_BOOK;
    RETURN check_avaliabillity;
END;
/

DECLARE 
    CHECK_AVALIABLE NUMBER;
BEGIN
    CHECK_AVALIABLE:=CHECKAVALIABILLITY(22445566);
    IF( CHECK_AVALIABLE = 1) THEN
        DBMS_OUTPUT.PUT_LINE('Available');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Not available');
    END IF;
END;
/

--FUNCTION TO SEE HOW MANY DAYS THE BOOKS IS BORROWED
CREATE OR REPLACE FUNCTION BORROWDATES(ISBN_BOOK IN BOOKS.ISBN%TYPE)
RETURN NUMBER
IS DAYS_BORROWED NUMBER;

BEGIN
SELECT DAYSBORROWED  INTO DAYS_BORROWED  
    FROM BORROWS b JOIN BOOKS bo ON b.BOOKISBN=bo.ISBN
    WHERE ISBN=ISBN_BOOK;
    RETURN DAYS_BORROWED;
END;
/

DECLARE 
    BORROWED_DAYS BORROWS.DAYSBORROWED%TYPE;
    
BEGIN
    BORROWED_DAYS:=BORROWDATES('35610290');
    DBMS_OUTPUT.PUT_LINE(BORROWED_DAYS);
END;
/

--FUNCTION TO CALCULATE FINE
CREATE OR REPLACE FUNCTION PAYFINE (ISBN_BOOK IN BOOKS.ISBN%TYPE)
RETURN FLOAT
IS FINE FLOAT;

DAYS_BORROWED NUMBER;

BEGIN
    SELECT DAYSBORROWED  INTO DAYS_BORROWED  
    FROM BORROWS b JOIN BOOKS bo ON b.BOOKISBN=bo.ISBN
    WHERE ISBN=ISBN_BOOK;
    
    IF (DAYS_BORROWED > 30)THEN
        FINE:=(10*DAYS_BORROWED)/100;
    END IF;
    RETURN FINE;
END;
/

DECLARE 
    FINE FLOAT;
BEGIN
    FINE:=PAYFINE(31209765);
    DBMS_OUTPUT.PUT_LINE(FINE);
END;
/

--A PROCEDURE THAT RETURNS A BOOK BY TITLE
CREATE OR REPLACE PROCEDURE BOOKINFO (BOOK_TITLE  IN BOOKS.TITLE%TYPE) AS
BEGIN
  DECLARE BOOK_ISBN BOOKS.ISBN%TYPE;
          BOOK_CATEGORY BOOKS.CATEGORY%TYPE;
          BOOK_WRITER BOOKS.WRITER%TYPE;
          CURSOR book IS 
            SELECT ISBN,WRITER,CATEGORY FROM BOOKS  WHERE TITLE=BOOK_TITLE;
  BEGIN
  OPEN book;
  LOOP
    FETCH book INTO BOOK_ISBN,BOOK_WRITER,BOOK_CATEGORY;
    EXIT WHEN book%NotFound; 
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('ISBN:'|| BOOK_ISBN);
  DBMS_OUTPUT.PUT_LINE('TITLE:'|| BOOK_TITLE);
  DBMS_OUTPUT.PUT_LINE('WRITER:'|| BOOK_WRITER);
  DBMS_OUTPUT.PUT_LINE('CATEGORY:'|| BOOK_CATEGORY);
 CLOSE book;

  
    END;
END;
/

EXEC BOOKINFO('Zazi in the train');

--A PROCECURE TO RETUTN A BOOK BY THE WRITER
CREATE OR REPLACE PROCEDURE BOOKINFO_W (BOOK_WRITER IN BOOKS.WRITER%TYPE) AS
BEGIN
  DECLARE BOOK_ISBN BOOKS.ISBN%TYPE;
          BOOK_CATEGORY BOOKS.CATEGORY%TYPE;
          BOOK_TITLE  BOOKS.TITLE%TYPE;
          CURSOR book IS 
            SELECT ISBN,TITLE,CATEGORY FROM BOOKS  WHERE WRITER=BOOK_WRITER;
  BEGIN
  OPEN book;
  LOOP
    FETCH book INTO BOOK_ISBN,BOOK_TITLE,BOOK_CATEGORY;
    EXIT WHEN book%NotFound;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('ISBN:'|| BOOK_ISBN);
  DBMS_OUTPUT.PUT_LINE('TITLE:'|| BOOK_TITLE);
  DBMS_OUTPUT.PUT_LINE('WRITER:'|| BOOK_WRITER);
  DBMS_OUTPUT.PUT_LINE('CATEGORY:'|| BOOK_CATEGORY);
  
CLOSE book;
  END;
END;
/

EXEC BOOKINFO_W('James Jous');

--A PROCEDURE TO BORROW A BOOK TO A MEMBER 
CREATE OR REPLACE PROCEDURE BORROWBOOK(M_NAME IN MEMBERS.NAME%TYPE,BOOK_TITLE IN BOOKS.TITLE%TYPE)
AS
 BEGIN
    DECLARE 
    BOOK_ISBN BOOKS.ISBN%TYPE;
    M_ID MEMBERS.ID%TYPE;
    BOOK_AVAIL BORROWS.AVALIABILLITY%TYPE;
    CURSOR book IS 
                SELECT b.ISBN,bo.AVALIABILLITY
                FROM BOOKS b JOIN BORROWS bo 
                ON b.ISBN=bo.BOOKISBN
                WHERE b.TITLE=BOOK_TITLE;
    BEGIN
        DBMS_OUTPUT.PUT_LINE('MEMBER:'||M_NAME||' WANTS TO BORROW BOOK WITH TITLE:'||BOOK_TITLE);
        OPEN book;
        LOOP
            FETCH book INTO BOOK_ISBN,BOOK_AVAIL;
            EXIT WHEN book%NotFound;
        END LOOP;
        SELECT ID INTO M_ID FROM MEMBERS WHERE NAME=M_NAME;
        --DBMS_OUTPUT.PUT_LINE(BOOK_AVAIL ||  BOOK_ISBN);
            IF (BOOK_AVAIL=1) THEN
                UPDATE BORROWS
                SET MEMBERID=M_ID WHERE BOOKISBN=BOOK_ISBN;
                
                UPDATE BORROWS 
                SET AVALIABILLITY=0 WHERE BOOKISBN=BOOK_ISBN;
                
                UPDATE BORROWS 
                SET BORROWDATE=sysdate WHERE BOOKISBN=BOOK_ISBN;
                
                UPDATE BORROWS 
                SET RETURNDATE=NULL WHERE BOOKISBN=BOOK_ISBN;
                
                UPDATE BORROWS 
                SET DAYSBORROWED=NULL WHERE BOOKISBN=BOOK_ISBN;
                
                DBMS_OUTPUT.PUT_LINE('DONE!');
                
            ELSE
                DBMS_OUTPUT.PUT_LINE('The book is not avaliable');
            END IF;
        
        CLOSE book;
        END;
 END;
 /

EXEC BORROWBOOK('Maria Kitsou','Olive again');
EXEC BORROWBOOK('John Doe','Me and you');
EXEC BORROWBOOK('Jane Eyer','Zazi in the train');

--A PROCEDURE TO RETURN A BOOK WHICH IS IN BORROW MODE
CREATE OR REPLACE PROCEDURE RETURNBORROWEDBOOK(BOOK_TITLE IN BOOKS.TITLE%TYPE)
AS
BEGIN
 DECLARE
        BOOK_ISBN BOOKS.ISBN%TYPE;
        BOOK_AVAIL BORROWS.AVALIABILLITY%TYPE;
        CURSOR book IS 
                SELECT b.ISBN,bo.AVALIABILLITY
                FROM BOOKS b JOIN BORROWS bo 
                ON b.ISBN=bo.BOOKISBN
                WHERE b.TITLE=BOOK_TITLE;

BEGIN
    OPEN book;
        LOOP
            FETCH book INTO BOOK_ISBN,BOOK_AVAIL;
            EXIT WHEN book%NotFound;
        END LOOP;
        --DBMS_OUTPUT.PUT_LINE(BOOK_ISBN  || BOOK_AVAIL);
        IF (BOOK_AVAIL=0) THEN
            DBMS_OUTPUT.PUT_LINE('Book must be returned');
            UPDATE BORROWS
            SET AVALIABILLITY=1 WHERE BOOKISBN=BOOK_ISBN;
            
            UPDATE BORROWS
            SET RETURNDATE=SYSDATE WHERE BOOKISBN=BOOK_ISBN;
            
            UPDATE BORROWS
            SET MEMBERID=null WHERE BOOKISBN=BOOK_ISBN;
            
            UPDATE BORROWS 
            SET DAYSBORROWED=(SELECT TO_DATE(BORROWS.RETURNDATE,'DD-MM-YYYY')- 
            TO_DATE (BORROWS.BORROWDATE,'DD-MM-YYYY')
            FROM DUAL);
            
        ELSE
            DBMS_OUTPUT.PUT_LINE('Book is avaliable');
        END IF;
    END;
END;
    /
 EXEC RETURNBORROWEDBOOK('Me and You');
 EXEC RETURNBORROWEDBOOK('Zazi in the train');
 
 --A PROCEDURE TO STORE A BOOK IN THE DATABASE
 CREATE OR REPLACE PROCEDURE INSERTBOOK(BOOK_TITLE IN BOOKS.TITLE%TYPE,
                                        BOOK_WRITER IN BOOKS.WRITER%TYPE,
                                        BOOK_ISBN IN BOOKS.ISBN%TYPE,
                                        BOOK_CATEGORY IN BOOKS.CATEGORY%TYPE
                                        )
AS
    BEGIN
    INSERT INTO BOOKS(TITLE,WRITER,ISBN,CATEGORY)VALUES(BOOK_TITLE,BOOK_WRITER,BOOK_ISBN,BOOK_CATEGORY);
END INSERTBOOK;
/

 EXEC INSERTBOOK('Flower','Sabine Bont',09872345,'Tales');
 
--A PROCEDURE TO INSERT A NEW MEMBER
CREATE OR REPLACE PROCEDURE INSERTMEMBER(M_ID IN MEMBERS.ID%TYPE,M_NAME IN MEMBERS.NAME%TYPE,M_ADDRESS IN MEMBERS.ADDRESS%TYPE)
AS
    BEGIN
    INSERT INTO MEMBERS(ID,NAME,ADDRESS)VALUES(M_ID,M_NAME,M_ADDRESS);
    END;
/
EXEC INSERTMEMBER(members_seq.nextval,'George Grigoriou','80 Selimon,Equador,BR');

--A PROCEDURE TO UPDATE THE RETURN DATE IN A STILL BORROWED BOOK
CREATE OR REPLACE PROCEDURE UPDATERETURNDATE(BOOK_ISBN IN BOOKS.ISBN%TYPE,RETURN_DATE IN BORROWS.RETURNDATE%TYPE)
AS
BEGIN 
 DECLARE
        BOOK_AVAIL BORROWS.AVALIABILLITY%TYPE;
        CURSOR book IS 
            SELECT bo.AVALIABILLITY
            FROM BOOKS b JOIN BORROWS bo 
            ON b.ISBN=bo.BOOKISBN
            WHERE b.ISBN=BOOK_ISBN;
 BEGIN           
    OPEN book;
    LOOP
        FETCH book INTO BOOK_AVAIL;
        EXIT WHEN book%NotFound;
    END LOOP; 
    
    IF(BOOK_AVAIL=1) THEN
        DBMS_OUTPUT.PUT_LINE('Book is still avaliable');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Book is still borrowed');
        UPDATE BORROWS
        SET RETURNDATE=RETURN_DATE WHERE BOOKISBN=BOOK_ISBN;
        
        UPDATE BORROWS
        SET AVALIABILLITY=1 WHERE BOOKISBN=BOOK_ISBN;
        
        UPDATE BORROWS
        SET MEMBERID=NULL WHERE BOOKISBN=BOOK_ISBN;
        
        UPDATE BORROWS
        SET DAYSBORROWED=(SELECT TO_DATE(BORROWS.RETURNDATE,'DD-MM-YYYY')- 
        TO_DATE (BORROWS.BORROWDATE,'DD-MM-YYYY')
        FROM DUAL);
    END IF;
    END;
END;
/
                
EXEC UPDATERETURNDATE(1563221,'15-08-2020');
EXEC UPDATERETURNDATE(91256109,'15-08-2020');

--PACKAGE BOOK_DB
CREATE OR REPLACE PACKAGE BOOK_DB AS
TYPE book_cur IS REF CURSOR;
FUNCTION BOOKPERCATEGORY(CAT BOOKS.CATEGORY%TYPE) RETURN book_cur;
PROCEDURE BOOKINFO (BOOK_TITLE IN BOOKS.TITLE%TYPE);
PROCEDURE BOOKINFO_W (BOOK_WRITER IN BOOKS.WRITER%TYPE);
PROCEDURE INSERTBOOK(BOOK_TITLE IN BOOKS.TITLE%TYPE,
                    BOOK_WRITER IN BOOKS.WRITER%TYPE,
                    BOOK_ISBN IN BOOKS.ISBN%TYPE,
                    BOOK_CATEGORY IN BOOKS.CATEGORY%TYPE);
END BOOK_DB;
/

CREATE OR REPLACE PACKAGE BODY BOOK_DB AS
            
FUNCTION BOOKPERCATEGORY(CAT BOOKS.CATEGORY%TYPE)
RETURN book_cur IS book_current book_cur;
BEGIN
    OPEN book_current FOR 
    SELECT ISBN 
    FROM BOOKS WHERE CATEGORY=cat;
    RETURN book_current;
END BOOKPERCATEGORY;


PROCEDURE BOOKINFO(BOOK_TITLE IN BOOKS.TITLE%TYPE) AS
BOOK_ISBN BOOKS.ISBN%TYPE;
BOOK_CATEGORY BOOKS.CATEGORY%TYPE;
BOOK_WRITER BOOKS.WRITER%TYPE;
CURSOR book IS 
    SELECT b.ISBN,b.WRITER,b.CATEGORY FROM BOOKS b WHERE b.TITLE=BOOK_TITLE;
    
  BEGIN
  OPEN book;
  LOOP
    FETCH book INTO BOOK_ISBN,BOOK_WRITER,BOOK_CATEGORY;
    EXIT WHEN book%NotFound; 
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('ISBN:'|| BOOK_ISBN);
  DBMS_OUTPUT.PUT_LINE('TITLE:'|| BOOK_TITLE);
  DBMS_OUTPUT.PUT_LINE('WRITER:'|| BOOK_WRITER);
  DBMS_OUTPUT.PUT_LINE('CATEGOTY:'|| BOOK_CATEGORY);
  CLOSE book;
END BOOKINFO;

PROCEDURE BOOKINFO_W (BOOK_WRITER IN BOOKS.WRITER%TYPE) AS
BOOK_ISBN BOOKS.ISBN%TYPE;
BOOK_CATEGORY BOOKS.CATEGORY%TYPE;
BOOK_TITLE  BOOKS.TITLE%TYPE;
CURSOR book IS 
    SELECT ISBN,TITLE,CATEGORY FROM BOOKS  WHERE WRITER=BOOK_WRITER;
    
  BEGIN  
  OPEN book;
  LOOP
    FETCH book INTO BOOK_ISBN,BOOK_TITLE,BOOK_CATEGORY;
    EXIT WHEN book%NotFound;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('ISBN:'|| BOOK_ISBN);
  DBMS_OUTPUT.PUT_LINE('TITLE:'|| BOOK_TITLE);
  DBMS_OUTPUT.PUT_LINE('WRITER:'|| BOOK_WRITER);
  DBMS_OUTPUT.PUT_LINE('CATEGOTY:'|| BOOK_CATEGORY);
  CLOSE book;
END BOOKINFO_W;

PROCEDURE INSERTBOOK(BOOK_TITLE IN BOOKS.TITLE%TYPE,
                    BOOK_WRITER IN BOOKS.WRITER%TYPE,
                    BOOK_ISBN IN BOOKS.ISBN%TYPE,
                    BOOK_CATEGORY IN BOOKS.CATEGORY%TYPE)
AS
    BEGIN
    INSERT INTO BOOKS(TITLE,WRITER,ISBN,CATEGORY)VALUES(BOOK_TITLE,BOOK_WRITER,BOOK_ISBN,BOOK_CATEGORY);
END INSERTBOOK;

END BOOK_DB;
/



--PACKAGE MEMBERS_DB
CREATE OR REPLACE PACKAGE MEMBERS_DB AS
 PROCEDURE INSERTMEMBER(M_ID IN MEMBERS.ID%TYPE,M_NAME IN MEMBERS.NAME%TYPE,M_ADDRESS IN MEMBERS.ADDRESS%TYPE);
END MEMBERS_DB;
/

CREATE  OR REPLACE PACKAGE BODY MEMBERS_DB AS
PROCEDURE INSERTMEMBER(M_ID IN MEMBERS.ID%TYPE,M_NAME IN MEMBERS.NAME%TYPE,M_ADDRESS IN MEMBERS.ADDRESS%TYPE)
IS
    BEGIN
    INSERT INTO MEMBERS(ID,NAME,ADDRESS)VALUES(M_ID,M_NAME,M_ADDRESS);
END INSERTMEMBER;
END MEMBERS_DB;
/

--PACKAGE BORROWS_DB
CREATE OR REPLACE PACKAGE BORROWS_DB AS
FUNCTION CHECKAVALIABILLITY(ISBN_BOOK IN BOOKS.ISBN%TYPE)RETURN NUMBER;
FUNCTION BORROWDATES(ISBN_BOOK IN BOOKS.ISBN%TYPE) RETURN NUMBER; 
FUNCTION PAYFINE (ISBN_BOOK IN BOOKS.ISBN%TYPE) RETURN FLOAT;
PROCEDURE BORROWBOOK(M_NAME IN MEMBERS.NAME%TYPE,BOOK_TITLE IN BOOKS.TITLE%TYPE);
PROCEDURE RETURNBORROWEDBOOK(BOOK_TITLE IN BOOKS.TITLE%TYPE);
PROCEDURE UPDATERETURNDATE(BOOK_ISBN IN BOOKS.ISBN%TYPE,RETURN_DATE IN BORROWS.RETURNDATE%TYPE);

END BORROWS_DB;
/

CREATE OR REPLACE PACKAGE BODY BORROWS_DB AS
FUNCTION CHECKAVALIABILLITY(ISBN_BOOK IN BOOKS.ISBN%TYPE)
RETURN NUMBER IS
check_avaliabillity NUMBER;

BEGIN 
    SELECT AVALIABILLITY INTO check_avaliabillity  
    FROM BORROWS b JOIN BOOKS bo ON b.BOOKISBN=bo.ISBN
    WHERE ISBN=ISBN_BOOK;
    RETURN check_avaliabillity;
END CHECKAVALIABILLITY;

FUNCTION BORROWDATES(ISBN_BOOK IN BOOKS.ISBN%TYPE)
RETURN NUMBER
AS DAYS_BORROWED NUMBER;

BEGIN
SELECT DAYSBORROWED  INTO DAYS_BORROWED  
    FROM BORROWS b JOIN BOOKS bo ON b.BOOKISBN=bo.ISBN
    WHERE ISBN=ISBN_BOOK;
    RETURN DAYS_BORROWED;
END BORROWDATES;

FUNCTION PAYFINE (ISBN_BOOK IN BOOKS.ISBN%TYPE)
RETURN FLOAT
IS FINE FLOAT;

DAYS_BORROWED NUMBER;

BEGIN
    SELECT DAYSBORROWED  INTO DAYS_BORROWED  
    FROM BORROWS b JOIN BOOKS bo ON b.BOOKISBN=bo.ISBN
    WHERE ISBN=ISBN_BOOK;
    
    IF (DAYS_BORROWED > 30)THEN
        FINE:=(10*DAYS_BORROWED)/100;
    END IF;
    RETURN FINE;
END PAYFINE;

PROCEDURE BORROWBOOK(M_NAME IN MEMBERS.NAME%TYPE,BOOK_TITLE IN BOOKS.TITLE%TYPE)
AS
  
    BOOK_ISBN BOOKS.ISBN%TYPE;
    M_ID MEMBERS.ID%TYPE;
    BOOK_AVAIL BORROWS.AVALIABILLITY%TYPE;
    CURSOR book IS 
                SELECT b.ISBN,bo.AVALIABILLITY
                FROM BOOKS b JOIN BORROWS bo 
                ON b.ISBN=bo.BOOKISBN
                WHERE b.TITLE=BOOK_TITLE;
    BEGIN
        DBMS_OUTPUT.PUT_LINE('MEMBER:'||M_NAME||' WANTS TO BORROW BOOK WITH TITLE:'||BOOK_TITLE);
        OPEN book;
        LOOP
            FETCH book INTO BOOK_ISBN,BOOK_AVAIL;
            EXIT WHEN book%NotFound;
        END LOOP;
        SELECT ID INTO M_ID FROM MEMBERS WHERE NAME=M_NAME;
        --DBMS_OUTPUT.PUT_LINE(BOOK_AVAIL ||  BOOK_ISBN);
            IF (BOOK_AVAIL=1) THEN
                UPDATE BORROWS
                SET MEMBERID=M_ID WHERE BOOKISBN=BOOK_ISBN;
                
                UPDATE BORROWS 
                SET AVALIABILLITY=0 WHERE BOOKISBN=BOOK_ISBN;
                
                UPDATE BORROWS 
                SET BORROWDATE=sysdate WHERE BOOKISBN=BOOK_ISBN;
                
                UPDATE BORROWS 
                SET RETURNDATE=NULL WHERE BOOKISBN=BOOK_ISBN;
                
                UPDATE BORROWS 
                SET DAYSBORROWED=NULL WHERE BOOKISBN=BOOK_ISBN;
                
                DBMS_OUTPUT.PUT_LINE('DONE!');
                
            ELSE
                DBMS_OUTPUT.PUT_LINE('The book is not avaliable');
            END IF;
        
        CLOSE book;
        END BORROWBOOK;
        
PROCEDURE RETURNBORROWEDBOOK(BOOK_TITLE IN BOOKS.TITLE%TYPE)
AS
        BOOK_ISBN BOOKS.ISBN%TYPE;
        BOOK_AVAIL BORROWS.AVALIABILLITY%TYPE;
        CURSOR book IS 
                SELECT b.ISBN,bo.AVALIABILLITY
                FROM BOOKS b JOIN BORROWS bo 
                ON b.ISBN=bo.BOOKISBN
                WHERE b.TITLE=BOOK_TITLE;

BEGIN
    OPEN book;
        LOOP
            FETCH book INTO BOOK_ISBN,BOOK_AVAIL;
            EXIT WHEN book%NotFound;
        END LOOP;
        --DBMS_OUTPUT.PUT_LINE(BOOK_ISBN  || BOOK_AVAIL);
        IF (BOOK_AVAIL=0) THEN
            DBMS_OUTPUT.PUT_LINE('Book must be returned');
            UPDATE BORROWS
            SET AVALIABILLITY=1 WHERE BOOKISBN=BOOK_ISBN;
            
            UPDATE BORROWS
            SET RETURNDATE=SYSDATE WHERE BOOKISBN=BOOK_ISBN;
            
            UPDATE BORROWS
            SET MEMBERID=null WHERE BOOKISBN=BOOK_ISBN;
            
            UPDATE BORROWS 
            SET DAYSBORROWED=(SELECT TO_DATE(BORROWS.RETURNDATE,'DD-MM-YYYY')- 
            TO_DATE (BORROWS.BORROWDATE,'DD-MM-YYYY')
            FROM DUAL);
            
        ELSE
            DBMS_OUTPUT.PUT_LINE('Book is avaliable');
        END IF;
    END RETURNBORROWEDBOOK;
    
PROCEDURE UPDATERETURNDATE(BOOK_ISBN IN BOOKS.ISBN%TYPE,RETURN_DATE IN BORROWS.RETURNDATE%TYPE)
AS

        BOOK_AVAIL BORROWS.AVALIABILLITY%TYPE;
        CURSOR book IS 
            SELECT bo.AVALIABILLITY
            FROM BOOKS b JOIN BORROWS bo 
            ON b.ISBN=bo.BOOKISBN
            WHERE b.ISBN=BOOK_ISBN;
 BEGIN           
    OPEN book;
    LOOP
        FETCH book INTO BOOK_AVAIL;
        EXIT WHEN book%NotFound;
    END LOOP; 
    DBMS_OUTPUT.PUT_LINE(BOOK_AVAIL);
    IF(BOOK_AVAIL=1) THEN
        DBMS_OUTPUT.PUT_LINE('Book is still avaliable');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Book is still borrowed');
        UPDATE BORROWS
        SET RETURNDATE=RETURN_DATE WHERE BOOKISBN=BOOK_ISBN;
        
        UPDATE BORROWS
        SET AVALIABILLITY=1 WHERE BOOKISBN=BOOK_ISBN;
        
        UPDATE BORROWS
        SET MEMBERID=NULL WHERE BOOKISBN=BOOK_ISBN;
        
        UPDATE BORROWS
        SET DAYSBORROWED=(SELECT TO_DATE(BORROWS.RETURNDATE,'DD-MM-YYYY')- 
        TO_DATE (BORROWS.BORROWDATE,'DD-MM-YYYY')
        FROM DUAL);
    END IF;
    END UPDATERETURNDATE;
END BORROWS_DB;
/

--CALL FUNCTIONS AND PROCEDURES THROUGH PACKAGES
SELECT BOOK_DB.BOOKPERCATEGORY('Art') FROM DUAL;
SELECT BORROWS_DB.CHECKAVALIABILLITY('78123100')  FROM DUAL;
EXEC BOOK_DB.BOOKINFO('Woman words');
EXEC BOOK_DB.BOOKINFO_W('Tefvik Fikret');
EXEC BOOK_DB.INSERTBOOK('Roses','Julia Robert',90876543,'Flowers'); 
EXEC MEMBERS_DB.INSERTMEMBER(members_seq.nextval,'Angie Jolie','80 Selimon,Equador,BR');
SELECT BORROWS_DB.BORROWDATES('31209765') FROM DUAL;
SELECT BORROWS_DB.PAYFINE('31209765') FROM DUAL;
EXEC BORROWS_DB.BORROWBOOK('Mike Eliot','Jermin');
EXEC BORROWS_DB.RETURNBORROWEDBOOK('Woman words');
EXEC BORROWS_DB.UPDATERETURNDATE(33556677,'15-08-2024');
