create table CUSTOMERS AS
select * FROM XSALES.customers; 

CREATE TABLE ORDERS AS
SELECT * FROM XSALES.orders;
--XSALES MIA BASI DEDOMENON
DROP TABLE CUSTOMERS;
DROP TABLE ORDERS;

--JOIN GIA NA DO TIS PARAGGELIES TOY KATHE PELATI
SELECT * FROM CUSTOMERS c JOIN ORDERS o ON o.customer_id =c.id;
SELECT COUNT (*) FROM CUSTOMERS c JOIN ORDERS o on o.customer_id=c.id;--synolo olo ton pelaton 

--EPILEGO APO AYTOYS TOYS PELATES  MARITAL_STATUS EINAI SINGLE 
-- SINGLE?, CREDIT_LIMIT=3000 KAI GENDER='MALE'
--EKSETAZEI O OPTIMIZER
EXPLAIN PLAN FOR
SELECT/*+ USE_MERG(c o)*/ c.id,name,credit_limit--USE NL(c o) ektokseuetai to kostos gt polles pleiades 
--pos na tis kanei join
FROM CUSTOMERS c JOIN ORDERS o ON o.customer_id=c.id
WHERE C.marital_status='single' AND credit_limit=15000 AND gender='Female';

--  EMPHANIZEI TA STOIXEIA TOU PLAN_TABLE
SELECT * FROM plan_table
START WITH id=0
CONNECT BY PRIOR id=parent_id;--EPANALHPTIKO JOIN 

--GIA NA DO TO KOSTOS TOY OPTIMIZER
DELETE FROM plan_table;

--FTIAXNO EYRETIRIO NA DO AN THA MPOREI NA EPITAXYNUOYN AYTA
--PIO GRHGORI EPILOGI TVN KASTOMERS KATHOS APOMONONO AYTOYW POY EXOYN 
--TO SYGKEKRIMENO MARITAL_STATUS
--THA MPOROYSA NA FTIAKSO EYRETHRIO GIA NA PARO TOYW FEMALE PELATES

CREATE INDEX MSINDEX ON CUSTOMERS(marital_status);
--PERIMENO NA MOY FEREI LIGOTERES PLEIADES
--O OPTIMIZER VRISKEI ENAN PIO GRIGORO TROPO NA TIS PLEIADES POY EXOYN
--TA XARAKTIRISTIKA
CREATE INDEX CLINDEX ON CUSTOMERS(credit_limit);

--DROP INDEXES 
DROP INDEX MSINDEX;
DROP INDEX CLINDEX;

--FTIAXNO BITMAP EYRETHRIA
--MOY DINOYN TA ROWID TON PLEIADON POY THELO
--KAI MIKRAINOYN PERISSOTERO
--TO COST 
--EXOUN MONO TIW DIAFORETIKES TIMES PX CREDIT_LIMITI STIO 1
--MARTIAL_STATUS KAI GENDER STO ALLO
--PAIRNEI TIN TOMI TVN 3 LISTVN
CREATE BITMAP INDEX CLINDEX ON CUSTOMERS(credit_limit);
CREATE BITMAP INDEX MSINDEX ON CUSTOMERS(marital_status);
CREATE BITMAP INDEX GINDEX ON CUSTOMERS(gender);
